image:
  name: hashicorp/terraform:1.0.0
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform
    - .terraform.lock.hcl

stages:
  - test
  - build
  - deploy

validate:
  stage: test
  before_script:
    - terraform --version
    - terraform init
  script:
    - terraform validate

plan:
  only:
    refs:
      - master
  stage: build
  script:
    - terraform plan -var-file=$TFVARSFILE -out $PLAN
  artifacts:
    name: tfplan
    expire_in: 1 week
    paths:
      - $PLAN

apply:
  when: manual
  only:
    refs:
      - master
  stage: deploy
  environment:
    name: production
  script:
    - terraform apply -auto-approve -var-file=$TFVARSFILE
