image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform

before_script:
  - terraform --version
  - terraform init

stages:
  - validate
  - build

validate:
  stage: validate
  script:
    - terraform validate -var-file=$TFVARSFILE

plan:
  stage: build
  script:
    - terraform plan -var-file=$TFVARSFILE -out $PLAN
  artifacts:
    name: plan
    paths:
      - $PLAN
