image:
  name: hashicorp/terraform:1.0.0
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform
    - .terraform.lock.hcl

before_script:
  - terraform --version
  - terraform init

stages:
  - test
  - build
  - deploy

validate:
  stage: test
  script:
    - terraform validate -var-file=$TFVARSFILE

plan:
  stage: build
  script:
    - terraform plan -var-file=$TFVARSFILE -out $PLAN
  artifacts:
    name: plan
    paths:
      - $PLAN

apply:
  stage: deploy
  script:
    - terraform apply -auto-approve -var-file=$TFVARSFILE
  when: manual
  only:
    - master
